name: Build Image and push to ECR

on:
  release:
    types: [created]
  push:
    branches:
      - deploy

jobs:
  decrypt-build-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - uses: kciter/aws-ecr-action@master
        with:
          access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          account_id: ${{ secrets.AWS_ACCOUNT_ID }}
          repo: kgs
          region: us-east-2
          dockerfile: ./Dockerfile
          tags: latest,${{ github.sha }}
          create_repo: true
